import type { Company, FilterChipModel, NavItem, SelectOption } from './types';

/** Left-nav destinations (icons are Material Symbols names). */
export const navItems: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', iconName: 'dashboard' },
  { id: 'companies', label: 'Companies', iconName: 'business' },
  { id: 'campaigns', label: 'Campaigns', iconName: 'campaign' },
  { id: 'jobs', label: 'Generation Jobs', iconName: 'smart_toy' },
  { id: 'drafts', label: 'Draft Review', iconName: 'rate_review' },
  { id: 'schedule', label: 'Schedule', iconName: 'calendar_today' },
  { id: 'audit', label: 'Audit Logs', iconName: 'history_edu' },
  { id: 'settings', label: 'Settings', iconName: 'settings' },
];

export const industryOptions: SelectOption[] = [
  { value: 'all', label: 'All Industries' },
  { value: 'software', label: 'Software Development' },
  { value: 'finance', label: 'Financial Services' },
  { value: 'healthcare', label: 'Healthcare' },
];

export const companySizeOptions: SelectOption[] = [
  { value: 'any', label: 'Any Size' },
  { value: '1-50', label: '1-50 Employees' },
  { value: '51-200', label: '51-200 Employees' },
  { value: '201-1000', label: '201-1000 Employees' },
  { value: '1000+', label: '1000+ Employees' },
];

export const locationOptions: string[] = [
  'Global',
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'India',
  'Brazil',
  'Japan',
  'China',
  'Singapore',
  'Netherlands',
  'Sweden',
  'Switzerland',
  'United Arab Emirates',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'Gabon',
  'Gambia',
  'Georgia',
  'Ghana',
  'Greece',
  'Guatemala',
  'Guinea',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'lb',
  'ls',
  'lr',
  'ly',
  'li',
  'lt',
  'lu',
  'mk',
  'mg',
  'mw',
  'my',
  'mv',
  'ml',
  'mt',
  'mh',
  'mr',
  'mu',
  'mx',
  'fm',
  'md',
  'mc',
  'mn',
  'me',
  'ma',
  'mz',
  'mm',
  'na',
  'nr',
  'np',
  'nz',
  'ni',
  'ne',
  'ng',
  'kp',
  'no',
  'om',
  'pk',
  'pw',
  'pa',
  'pg',
  'py',
  'pe',
  'ph',
  'pl',
  'pt',
  'qa',
  'ro',
  'ru',
  'rw',
  'kn',
  'lc',
  'vc',
  'ws',
  'sm',
  'st',
  'sa',
  'sn',
  'rs',
  'sc',
  'sl',
  'sk',
  'si',
  'sb',
  'so',
  'za',
  'kr',
  'ss',
  'es',
  'lk',
  'sd',
  'sr',
  'sz',
  'sy',
  'tw',
  'tj',
  'tz',
  'th',
  'tl',
  'tg',
  'to',
  'tt',
  'tn',
  'tr',
  'tm',
  'tv',
  'ug',
  'ua',
  'uy',
  'uz',
  'vu',
  'va',
  've',
  'vn',
  'ye',
  'zm',
  'zw',
];

/** States, provinces, and regions for drill-down location selection. */
export const subRegions: Record<string, string[]> = {
  'United States': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ],
  Canada: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
  ],
  'United Kingdom': ['England', 'Scotland', 'Wales', 'Northern Ireland'],
  Australia: [
    'New South Wales',
    'Victoria',
    'Queensland',
    'Western Australia',
    'South Australia',
    'Tasmania',
    'Australian Capital Territory',
    'Northern Territory',
  ],
  Germany: [
    'Baden-Württemberg',
    'Bavaria',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hesse',
    'Lower Saxony',
    'Mecklenburg-Vorpommern',
    'North Rhine-Westphalia',
    'Rhineland-Palatinate',
    'Saarland',
    'Saxony',
    'Saxony-Anhalt',
    'Schleswig-Holstein',
    'Thuringia',
  ],
  France: [
    'Auvergne-Rhône-Alpes',
    'Bourgogne-Franche-Comté',
    'Brittany',
    'Centre-Val de Loire',
    'Corsica',
    'Grand Est',
    'Hauts-de-France',
    'Île-de-France',
    'Normandy',
    'Nouvelle-Aquitaine',
    'Occitanie',
    'Pays de la Loire',
    'Provence-Alpes-Côte d’Azur',
  ],
  India: [
    'Andhra Pradesh',
    'Karnataka',
    'Kerala',
    'Maharashtra',
    'Tamil Nadu',
    'Telangana',
    'Uttar Pradesh',
    'West Bengal',
    'Delhi',
    'Gujarat',
  ],
  Brazil: [
    'São Paulo',
    'Rio de Janeiro',
    'Minas Gerais',
    'Paraná',
    'Rio Grande do Sul',
    'Santa Catarina',
  ],
  Japan: [
    'Aichi',
    'Chiba',
    'Fukuoka',
    'Hokkaido',
    'Hyogo',
    'Kanagawa',
    'Kyoto',
    'Osaka',
    'Saitama',
    'Tokyo',
  ],
  China: [
    'Beijing',
    'Shanghai',
    'Guangdong',
    'Zhejiang',
    'Jiangsu',
    'Sichuan',
    'Fujian',
    'Hubei',
  ],
};

/** Cities for drill-down location selection, keyed by "Country, Region". */
export const cityOptionsMap: Record<string, string[]> = {
  'United States, California': [
    'San Francisco',
    'Los Angeles',
    'San Diego',
    'San Jose',
    'Palo Alto',
    'Mountain View',
    'Irvine',
    'Sacramento',
    'Oakland',
    'Fremont',
    'Santa Monica',
    'Redwood City',
    'Santa Clara',
  ],
  'United States, New York': [
    'New York City',
    'Brooklyn',
    'Buffalo',
    'Albany',
    'Rochester',
    'Yonkers',
    'Syracuse',
    'Long Island City',
  ],
  'United States, Texas': [
    'Austin',
    'Houston',
    'Dallas',
    'San Antonio',
    'Fort Worth',
    'El Paso',
    'Arlington',
    'Plano',
    'Irving',
  ],
  'United States, Florida': [
    'Miami',
    'Orlando',
    'Tampa',
    'Jacksonville',
    'Fort Lauderdale',
    'St. Petersburg',
    'Hialeah',
  ],
  'United States, Washington': [
    'Seattle',
    'Bellevue',
    'Redmond',
    'Tacoma',
    'Spokane',
    'Vancouver',
    'Everett',
  ],
  'United States, Massachusetts': [
    'Boston',
    'Cambridge',
    'Worcester',
    'Somerville',
    'Newton',
    'Quincy',
  ],
  'United States, Illinois': ['Chicago', 'Naperville', 'Aurora', 'Rockford', 'Joliet'],
  'Canada, Ontario': [
    'Toronto',
    'Ottawa',
    'Mississauga',
    'Brampton',
    'Hamilton',
    'Waterloo',
    'London',
    'Burlington',
    'Oshawa',
    'Sarnia',
    'Kitchener',
    'Markham',
    'Vaughan',
    'Windsor',
    'Oakville',
    'Guelph',
    'Thunder Bay',
    'Kingston',
  ],
  'Canada, Quebec': [
    'Montreal',
    'Quebec City',
    'Laval',
    'Gatineau',
    'Longueuil',
    'Sherbrooke',
    'Saguenay',
    'Lévis',
  ],
  'Canada, British Columbia': [
    'Vancouver',
    'Victoria',
    'Burnaby',
    'Surrey',
    'Richmond',
    'Kelowna',
    'Coquitlam',
    'Kamloops',
  ],
  'Canada, Alberta': ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge', 'St. Albert'],
  'United Kingdom, England': [
    'London',
    'Manchester',
    'Birmingham',
    'Bristol',
    'Leeds',
    'Liverpool',
    'Newcastle',
    'Sheffield',
    'Reading',
    'Cambridge',
    'Oxford',
    'Nottingham',
  ],
  'United Kingdom, Scotland': ['Glasgow', 'Edinburgh', 'Aberdeen', 'Dundee'],
  'United Kingdom, Wales': ['Cardiff', 'Swansea', 'Newport'],
  'Australia, New South Wales': [
    'Sydney',
    'Newcastle',
    'Wollongong',
    'Central Coast',
    'Parramatta',
  ],
  'Australia, Victoria': ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo'],
  'Australia, Queensland': ['Brisbane', 'Gold Coast', 'Sunshine Coast', 'Townsville'],
  'Germany, Bavaria': ['Munich', 'Nuremberg', 'Augsburg', 'Regensburg', 'Erlangen'],
  'Germany, Berlin': ['Berlin'],
  'Germany, Hamburg': ['Hamburg'],
  'Germany, North Rhine-Westphalia': [
    'Cologne',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Bonn',
    'Bielefeld',
    'Münster',
  ],
  'Germany, Hesse': ['Frankfurt', 'Wiesbaden', 'Kassel', 'Darmstadt'],
  'France, Île-de-France': [
    'Paris',
    'Boulogne-Billancourt',
    'Saint-Denis',
    'Versailles',
    'Nanterre',
  ],
  'France, Auvergne-Rhône-Alpes': ['Lyon', 'Saint-Étienne', 'Grenoble', 'Villeurbanne'],
  'France, Provence-Alpes-Côte d’Azur': ['Marseille', 'Nice', 'Toulon', 'Aix-en-Provence'],
  'India, Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Thane'],
  'India, Karnataka': ['Bengaluru', 'Mysuru', 'Hubballi', 'Mangaluru'],
  'India, Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Salem'],
  'India, Telangana': ['Hyderabad', 'Warangal', 'Nizamabad'],
  'India, Delhi': ['New Delhi', 'Delhi', 'Noida', 'Gurgaon'],
  'India, Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot'],
  'Brazil, São Paulo': ['São Paulo', 'Campinas', 'Guarulhos', 'Santos', 'São Bernardo do Campo'],
  'Brazil, Rio de Janeiro': ['Rio de Janeiro', 'Niterói', 'Duque de Caxias', 'São Gonçalo'],
  'Japan, Tokyo': ['Shinjuku', 'Shibuya', 'Minato', 'Chiyoda', 'Chuo', 'Setagaya', 'Nerima'],
  'Japan, Osaka': ['Osaka', 'Sakai', 'Higashiosaka', 'Suita'],
  'Japan, Kanagawa': ['Yokohama', 'Kawasaki', 'Sagamihara', 'Fujisawa'],
  'China, Guangdong': ['Guangzhou', 'Shenzhen', 'Dongguan', 'Foshan', 'Huizhou'],
  'China, Beijing': ['Beijing'],
  'China, Shanghai': ['Shanghai'],
};

export const initialFilterChips: FilterChipModel[] = [
  { id: 'size', label: 'Size: 51-200' },
  { id: 'tech', label: 'Tech: React' },
];

export const discoveryMatches = 1240;

export const companies: Company[] = [
  {
    id: 'acme',
    name: 'Acme Corp',
    domain: 'acme.io',
    initial: 'A',
    industry: 'SaaS / Enterprise',
    location: 'San Francisco, CA',
    size: '150-200',
    techStack: ['React', 'AWS'],
    confidence: 98,
    confidenceTone: 'positive',
  },
  {
    id: 'nexus',
    name: 'Nexus Dynamics',
    domain: 'nexus.dev',
    initial: 'N',
    industry: 'Fintech',
    location: 'New York, NY',
    size: '50-100',
    techStack: ['Vue', 'Stripe'],
    confidence: 92,
    confidenceTone: 'positive',
  },
  {
    id: 'orbit',
    name: 'Orbit Logistics',
    domain: 'orbit.logistics',
    initial: 'O',
    industry: 'Supply Chain',
    location: 'Chicago, IL',
    size: '200-500',
    techStack: ['Angular', 'Azure'],
    confidence: 75,
    confidenceTone: 'neutral',
  },
];

/** Companies selected by default (matches the reference screen). */
export const defaultSelectedIds: string[] = ['acme', 'nexus'];
